### PR TITLE
Runtime - get rid of external calls to date and use bash internal SEC…

### PR DESCRIPTION
**Pull request by PeterPitterling**
…ONDS

each call to date takes 30-40ms and also includes fork/clone descriptor handling
SECONDS is anyway tracked by bash and therefore for free

### CODE REVIEW

**Review by fmherschel — COMMENTED** [review]
@angelabriel: Needs to be checked, if that is compatible with all currently supported SLES versions.

**Review by angelabriel — CHANGES_REQUESTED** [review]
@PeterPitterling 
date '+%s' and shell variable $SECONDS does not give the same result.
May be you mean $EPOCHSECONDS instead?

**Comment by PeterPitterling** [comment]
> @PeterPitterling date '+%s' and shell variable $SECONDS does not give the same result. May be you mean $EPOCHSECONDS instead?

the times timeA and timeB are only used for delta calculation to output the runtime of the current RA execution. The exact value of date +%s or EPOCHSECONDS are not required. 

Coding could probably even more simplified as the delta calculation might not be necessary as SECONDS is providing the time since shell invocation?!

**Review by angelabriel — APPROVED** [review]
Looks good to me, thanks

**Pull request merged**
