### PR TITLE
change default values for some action timouts to match official recommendations

### PR DESCRIPTION
**Pull request by fdanapfel**
See issue https://github.com/SUSE/SAPHanaSR/issues/33 for further discussion on this.

### CODE REVIEW

**Comment by fdanapfel** [comment]
> @fdanapfel : In my opinion the demote action should not be increased to 3600s.
> Normally the demote action is nearly empty. There is not action to demote a primary. In our documentation
> we do not set the demote action timeout (by intention)

@fmherschel: in that case, is the old default of 320s really necessary, or would it be OK to use a much lower default value for the demote timeout, like 60s?

**Comment by fmherschel** [comment]
> > @fdanapfel : In my opinion the demote action should not be increased to 3600s.
> > Normally the demote action is nearly empty. There is not action to demote a primary. In our documentation
> > we do not set the demote action timeout (by intention)
> 
> @fmherschel: in that case, is the old default of 320s really necessary, or would it be OK to use a much lower default value for the demote timeout, like 60s?

I would like to keep the old value of 320s. Once we really know the defaults pacemaker is running,
if the value is not set in the action parameters we can shorten the timeout. I want to avoid to break
customer clusters. I am still not sure which default pacemaker is taking.

**Comment by fdanapfel** [comment]
@fmherschel: OK, makes sense. I've now  added another commit to the PR to change the demote timeout back to the previous value.

**Comment by fdanapfel** [comment]
@angelabriel: thanks for the review. Will you or @fmherschel be able to merge this PR?

**Pull request merged**
